### ISSUE TITLE
Difference in read number between fastq and bam files

### ISSUE THREAD

**Issue by mniederhuber** [mckaylabunc/cutNrun-pipeline#14]
This is likely not an actual issue with the pipeline but something I'm not understanding. Adding an issue here to document.

I am finding that the number of reads counted in a `.fastq.gz` match what is reported by HTSF, and `bowtie2` std.out , BUT are significantly lower than what I count "by hand" in the corresponding `.bam` files. 

Using `samtools view -c ` to count reads in bam files, and have tried filtering on various flags for mapped or unmapped reads but consistently get millions more reads counted compared to the fastq file. Using the `_trim.bam` files.

Using `echo $(zcat yourfile.fastq.gz|wc -l)/4|bc` to count reads in the raw fastq file. 

Example:
``` 
| sample          | fastq      | bam        |
|-----------------|------------|------------|
| osaGFP.sup.rep1 | 31,827,468 | 40,891,146 |
```

I've looked at by the osaGFP CnR and older CtBP CnR and the difference is in both. 
Has anyone else encountered this? What am I missing?

**Comment by mniederhuber** [comment]
My understanding is that we run `bowtie2` such that only the best alignment for each read-pair is reported, ie. there shouldn't be repeated entries for the same pair in the sam or bam files.

**Comment by mniederhuber** [comment]
Think I figured this out. 
Counting reads in the fastq file is for either `R1` or `R2`, and the number reported by HTSF corresponds to read pairs.
`bowtie2` returns 2 entries for each read-pair corresponding to mate1 and mate2, ie individual aligned reads. 
But for the summary file `bowtie2` reports, the numbers in terms of pairs.

So...
``` 
| sample          | fastq read pairs | aligned pairs | bam aligned reads |
|-----------------|------------------|---------------|-------------------|
| osaGFP.sup.rep1 | 31,827,468       | 20,445,573    | 40,891,146        |
```

**Comment by snystrom** [comment]
Running bowtie2 with the `--unal` flag drops any unaligned reads from the output bam file, which I bet makes up the difference.
