### ISSUE TITLE
Jobs running less than 1 minute

### ISSUE THREAD

**Issue by 14stutzmanav** [mckaylabunc/cutNrun-pipeline#5]
There are several steps which generate jobs that only run for a minute. According to UNC ITS, such jobs should be run on the login node and not submitted to the cluster. Users who submit so many short jobs are penalized and have reduced access to resources.

The solution is to merge multiple rules into one. The rules causing jobs that run for under a minute are as follows:
- splitFragments
- makeFragmentBedGraphs
- makeSpikeNormFragmentBedGraphs
- convertToBigWig
- zNormBigWig
- callThresholdPeaks

**Comment by half-adder** [comment]
Wow. I didn't realize that this would cause such a penalty. I feel like this might affect other pipelines too?

**Comment by snystrom** [comment]
Hey noticed this pop up. FWIW a quick fix to this is to use the snakmake `localrules` feature.

Adding 
`localrules: all, splitFragments, makeFragmentBedGraphs, makeSpikeNormFragmentBedGraphs, convertToBigWig, zNormBigWig, callThresholdPeaks` just before `rule all` in the Snakefile will cause those rules to run on the head node.

I am a bit surprised, however, that some of these steps are running < 1 minute. I think this will probably depend on the dataset? Do your samples have less read depth than usual? If not, I am probably just wrong about runtime estimates, but the `localrules` thing should fix it.

**Comment by half-adder** [comment]
@14stutzmanav 🤦

**Comment by 14stutzmanav** [comment]
@mniederhuber, it's possible (but I think unlikely) that we'd get yelled at for that. We'll have to keep an eye on how many resources our jobs are actually using vs. what our Snakemake config is set up to request when we run this in the future. I've run this CnR pipeline for 3 separate CnR antibodies (with very different read depths) and observed very short run times regardless of the input sample. That makes me feel comfortable running these on the login node because regardless of input at the start, these steps are running very quickly.

**Comment by 14stutzmanav** [comment]
I've implemented @snystrom's fix and pushed it to our master branch. We can discuss whether to keep this commit in this week's lab meeting. https://github.com/mckaylabunc/cutNrun-pipeline/commit/e5220f30695ed58e83c0e13c97c08b2ef3470f97

**Comment by mniederhuber** [comment]
Awesome! Thanks @14stutzmanav

**Comment by 14stutzmanav** [comment]
I just reversed the "fix" using localrules for the jobs that run for less than one minute after Sean got a "don't run things in the head node" email from ITS. Now, steps that were generating jobs with short run times have been grouped together and should run as one single job. https://github.com/mckaylabunc/cutNrun-pipeline/commit/24531201206d9114347375d8e3a2e89623c218b4
