### ISSUE TITLE
combine_technical_reps

### ISSUE THREAD

**Issue by 14stutzmanav** [mckaylabunc/cutNrun-pipeline#6]
Combine_technical_reps is exhibiting strange behavior where it does not populate fastq files to cat into a merged rep file. Here is an example slurm.err output:

> /pine/scr/a/l/alexisv7/cnr-analysis/cutNrun-pipeline-k9me3-test/preProcessSampleConfig.py:40: FutureWarning: read_table is deprecated, use read_csv instead.
  df = pd.read_table(path, delimiter = fileDelimiter)
Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 1 (use --cores to define parallelism)
Rules claiming more threads will be scaled down.
Job counts:
        count   jobs
        1       combine_technical_reps
        1   
>
>[Mon Jan 10 12:54:02 2022]
rule combine_technical_reps:
    output: Fastq/hp1a2-3LW-wing-CnR-K9me3-sup_merged_R1.fastq.gz, Fastq/hp1a2-3LW-wing-CnR-K9me3-sup_merged_R2.fastq.gz
    jobid: 0
    wildcards: sample=hp1a2-3LW-wing-CnR-K9me3-sup_merged
>
>[Mon Jan 10 12:54:02 2022]
Error in rule combine_technical_reps:
    jobid: 0
    output: Fastq/hp1a2-3LW-wing-CnR-K9me3-sup_merged_R1.fastq.gz, Fastq/hp1a2-3LW-wing-CnR-K9me3-sup_merged_R2.fastq.gz
 >   shell:
 >   
>                cat  > Fastq/hp1a2-3LW-wing-CnR-K9me3-sup_merged_R1.fastq.gz &&
>                cat  > Fastq/hp1a2-3LW-wing-CnR-K9me3-sup_merged_R2.fastq.gz
>    
>        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)
>
>Shutting down, this might take some time.
>Exiting because a job execution failed. Look above for error message

**Comment by 14stutzmanav** [comment]
And here's my sampleInfo shee
[sampleInfo.txt](https://github.com/mckaylabunc/cutNrun-pipeline/files/7841517/sampleInfo.txt)
t

**Comment by 14stutzmanav** [comment]
Okay, the issue is actually slightly different. I figured out that the files which didn't populate anything for `cat` were ones that I made a custom "merged" entry for in my `sampleInfo.tsv` sheet. The actual problem is that combine_technical_reps doesn't actually combine tech reps. Instead, it copies the `fastq_r1` and `fastq_r2` files from `sampleInfo`.tsv to `Fastq` in your working directory with a corrected name.

We now need this step to cat multiple replicates into `merged_R1.fastq.gz` and `merged_R2.fastq.gz` files.

**Comment by snystrom** [comment]
This step is for pooling technical replicates (ie resequencing the same library). The pipeline currently doesn't pool biological replicates cause I ran out of time to implement this feature (see: https://github.com/snystrom/cutNrun-pipeline/issues/1). You could mirror this behavior by rerunning the pipeline but change the baseNameCols to be everything except the "rep" column. Then it would treat biological reps as technical replicates for analysis.

**Comment by 14stutzmanav** [comment]
Incredible! I'll close this issue and implement biological replicate combinations in response to https://github.com/snystrom/cutNrun-pipeline/issues/1.

**Comment by snystrom** [comment]
The bones for the pooling feature are found in the `faire-pipeline` though (which I did have time to implement). See all the lines that referr to the `poolSampleSheet` (https://github.com/snystrom/faire-pipeline/blob/master/Snakefile).

It's kind of a poor implementation in the faire-pipeline, since I duplicate rules for pooled samples. The better way to do it is to use something like "{sample}-pool" in rule all for the "{sample}" wildcard then the DAG should be able to figure it out.

**Comment by snystrom** [comment]
then you write 1 special rule for pooling reps after alignment that takes as input something like:

`expand("{sample}_whatever.bam", sample = lambda wildcards : sampleSheet[sampleSheet.baseName == wildcards.sample].baseName)`

and outputs: `{sample}-pooled_whatever.bam`, then for subsequent rules, if "{sample}-pooled" is passed in rule all, all rules referring to `{sample}` will implicitly also catch `{sample}-pooled`.

**Comment by snystrom** [comment]
Sorry for leaving you guys this mess.

**Comment by 14stutzmanav** [comment]
Don't be! You've given us a beautiful pipeline to begin and now I can go through and fine-tune it. It's not a mess!

**Comment by snystrom** [comment]
To expand on what I mean about the `rule all` bit. If you add inputs that look for `{sample}-pooled` outputs, then that will get pattern matched into all the `{sample}` wildcards in subsequent rules. For instance:

```
rule all:
    input:
        expand("BigWig/{sample}-pooled_{species}_trim_q5_dupsRemoved_{fragType}{normType}.{ftype}", sample = sampleSheet.baseName, species = REFGENOME, fragType = fragTypes, normType = normTypeList, ftype = {"bw", "bg"})
rule pool_reps:
    input:
        expand("Bam/{sample}_" + combinedGenome + "_trim_q5_dupsRemoved.bam", sample = sampleSheet.baseName)
    output:
        "Bam/{sample}_" + combinedGenome + "-pooled_trim_q5_dupsRemoved.bam"
    shell:
        """
        samtools merge {input} > {output}
        """


```

**Comment by 14stutzmanav** [comment]
Do I still need to do all the stuff in the beginning with setting up a poolSampleSheet?

**Comment by snystrom** [comment]
Technically no, but if you want it to output a pooledSampleSheet.csv then it could be helpful, but not required!

**Comment by 14stutzmanav** [comment]
Okay, and I also need to add a rule where it combines bio reps, right?

**Comment by snystrom** [comment]
Correct. similar to the one I just posted.

**Comment by 14stutzmanav** [comment]
Duh. I'm sorry, I though that was something else. Okay, I'm trying this out now! 🤞

**Comment by snystrom** [comment]
All good!

**Comment by 14stutzmanav** [comment]
So then in rule all, do I need to add a line for `{sample}-pooled` for all the rules that come after `pool_reps`?

**Comment by snystrom** [comment]
Yeah. There is a lot of excess stuff in rule all right now, so it makes some extra work for you, unfortunately. I would just do it for all the ones pointing to outputs in `BigWig/` `Bam/` `Plots/` `Peaks` and `threshold_peaks/`, if that makes sense.

**Comment by snystrom** [comment]
literally just copy the lines & add the `-pooled` bit.

**Comment by 14stutzmanav** [comment]
That's alright. I can do that. I did get an error when I did a dry-run. Note that I only added the {sample}_pooled line for the Bigwig output as you had in your example. Here's the error:

> AmbiguousRuleException:
> Rules removeDups and pool_reps are ambiguous for the file Bam/HWT-3LW-wing-CnR-K9me3-sup-rep1-pooled_dm6-sacCer3_trim_q5_dupsRemoved.bam.
> Consider starting rule output with a unique prefix, constrain your wildcards, or use the ruleorder directive.
> Wildcards:
> 	removeDups: sample=HWT-3LW-wing-CnR-K9me3-sup-rep1-pooled
> 	pool_reps: sample=HWT-3LW-wing-CnR-K9me3-sup-rep1
> Expected input files:
> 	removeDups: Bam/HWT-3LW-wing-CnR-K9me3-sup-rep1-pooled_dm6-sacCer3_trim_q5_dupsMarked.bam
> 	pool_reps: Bam/HWT-3LW-wing-CnR-K9me3-sup-rep1_dm6-sacCer3_trim_q5_dupsRemoved.bam Bam/HWT-3LW-wing-CnR-K9me3-sup-rep2_dm6-sacCer3_trim_q5_dupsRemoved.bam Bam/HWT-3LW-wing-CnR-K9me3-sup-rep3_dm6-sacCer3_trim_q5_dupsRemoved.bam Bam/K9R-3LW-wing-CnR-K9me3-sup-rep1_dm6-sacCer3_trim_q5_dupsRemoved.bam Bam/K9R-3LW-wing-CnR-K9me3-sup-rep2_dm6-sacCer3_trim_q5_dupsRemoved.bam Bam/K9R-3LW-wing-CnR-K9me3-sup-rep3_dm6-sacCer3_trim_q5_dupsRemoved.bam Bam/yw-3LW-wing-CnR-K9me3-sup-rep1_dm6-sacCer3_trim_q5_dupsRemoved.bam Bam/yw-3LW-wing-CnR-K9me3-sup-rep2_dm6-sacCer3_trim_q5_dupsRemoved.bam Bam/yw-3LW-wing-CnR-K9me3-sup-rep3_dm6-sacCer3_trim_q5_dupsRemoved.bam Bam/HWT-3LW-wing-CnR-K9me3-pel-rep1_dm6-sacCer3_trim_q5_dupsRemoved.bam Bam/HWT-3LW-wing-CnR-K9me3-pel-rep2_dm6-sacCer3_trim_q5_dupsRemoved.bam Bam/HWT-3LW-wing-CnR-K9me3-pel-rep3_dm6-sacCer3_trim_q5_dupsRemoved.bam Bam/K9R-3LW-wing-CnR-K9me3-pel-rep1_dm6-sacCer3_trim_q5_dupsRemoved.bam Bam/K9R-3LW-wing-CnR-K9me3-pel-rep2_dm6-sacCer3_trim_q5_dupsRemoved.bam Bam/K9R-3LW-wing-CnR-K9me3-pel-rep3_dm6-sacCer3_trim_q5_dupsRemoved.bam Bam/yw-3LW-wing-CnR-K9me3-pel-rep1_dm6-sacCer3_trim_q5_dupsRemoved.bam Bam/yw-3LW-wing-CnR-K9me3-pel-rep2_dm6-sacCer3_trim_q5_dupsRemoved.bam Bam/yw-3LW-wing-CnR-K9me3-pel-rep3_dm6-sacCer3_trim_q5_dupsRemoved.bam Bam/hp1a2-3LW-wing-CnR-K9me3-sup-rep1_dm6-sacCer3_trim_q5_dupsRemoved.bam Bam/hp1a2-3LW-wing-CnR-K9me3-pel-rep1_dm6-sacCer3_trim_q5_dupsRemoved.bam Bam/ywdf-3LW-wing-CnR-K9me3-sup-rep1_dm6-sacCer3_trim_q5_dupsRemoved.bam Bam/ywdf-3LW-wing-CnR-K9me3-pel-rep1_dm6-sacCer3_trim_q5_dupsRemoved.bam Bam/hp1a2-3LW-wing-CnR-K9me3-sup-rep2_dm6-sacCer3_trim_q5_dupsRemoved.bam Bam/hp1a2-3LW-wing-CnR-K9me3-pel-rep2_dm6-sacCer3_trim_q5_dupsRemoved.bam Bam/ywdf-3LW-wing-CnR-K9me3-pel-rep2_dm6-sacCer3_trim_q5_dupsRemoved.bam Bam/hp1a2-3LW-wing-CnR-K9me3-sup-rep3_dm6-sacCer3_trim_q5_dupsRemoved.bam Bam/hp1a2-3LW-wing-CnR-K9me3-pel-rep3_dm6-sacCer3_trim_q5_dupsRemoved.bam Bam/ywdf-3LW-wing-CnR-K9me3-pel-rep3_dm6-sacCer3_trim_q5_dupsRemoved.bam Bam/hp1a2-3LW-wing-CnR-K9me3-sup-rep4_dm6-sacCer3_trim_q5_dupsRemoved.bam Bam/hp1a2-3LW-wing-CnR-K9me3-pel-rep4_dm6-sacCer3_trim_q5_dupsRemoved.bam Bam/ywdf-3LW-wing-CnR-K9me3-sup-rep4_dm6-sacCer3_trim_q5_dupsRemoved.bam Bam/ywdf-3LW-wing-CnR-K9me3-pel-rep4_dm6-sacCer3_trim_q5_dupsRemoved.bamExpected output files:
> 	removeDups: Bam/HWT-3LW-wing-CnR-K9me3-sup-rep1-pooled_dm6-sacCer3_trim_q5_dupsRemoved.bam Bam/HWT-3LW-wing-CnR-K9me3-sup-rep1-pooled_dm6-sacCer3_trim_q5_dupsRemoved.bam.bai
> 	pool_reps: Bam/HWT-3LW-wing-CnR-K9me3-sup-rep1-pooled_dm6-sacCer3_trim_q5_dupsRemoved.bam

**Comment by snystrom** [comment]
Try changing the pool_reps rule to merge bams after the dupRemoval step instead.

**Comment by 14stutzmanav** [comment]
Just did that (great minds think alike!) but got the same error.

**Comment by snystrom** [comment]
The issue is because it's filling in `-pooled` into the removeDups rule as input. Set a wildcard constraint in the `removeDups` rule:

```
wildcard_constraints:                                                                                                                                                            
        sample ="(?!-pooled).*"   
```

**Comment by snystrom** [comment]
This is telling snakemake to not use any files that have `-pooled` in the `{sample}` wildcard as input to removeDups.

**Comment by 14stutzmanav** [comment]
Hmmm... I'm still getting the same error. Perhaps an issue with how wildcard_constraints is written..? 🤔

**Comment by snystrom** [comment]
Yeah. I might've written it wrong.

**Comment by snystrom** [comment]
```
rule removeDups:
	input:
		'Bam/{sample, (!?-pooled)}_' + combinedGenome + '_trim_q5_dupsMarked.bam'
	output:
		bam = 'Bam/{sample}_' +  combinedGenome + '_trim_q5_dupsRemoved.bam',
		index = 'Bam/{sample}_' + combinedGenome + '_trim_q5_dupsRemoved.bam.bai'
	envmodules:
		modules['samtoolsVer']
	shell:
		"""
		samtools view -@ 4 -bF 0x400 {input} > {output.bam} &&
		samtools index {output.bam} {output.index}
		"""
```

Maybe tweak it to use inline constraints?

**Comment by 14stutzmanav** [comment]
Same error.

I also tried 
```
wildcard_constraints:                                                                                                                                                            
        sample =".*(?!-pooled)"   
```

        
I got the following error
```
[alexisv7@longleaf-login4 cutNrun-pipeline-bioReps]$ bash dryrunSnakemake.sh Snakefile 
/pine/scr/a/l/alexisv7/cnr-analysis/cutNrun-pipeline-bioReps/preProcessSampleConfig.py:40: FutureWarning: read_table is deprecated, use read_csv instead.
  df = pd.read_table(path, delimiter = fileDelimiter)
Building DAG of jobs...
MissingInputException in line 347 of /pine/scr/a/l/alexisv7/cnr-analysis/cutNrun-pipeline-bioReps/Snakefile:
Missing input files for rule splitSpecies:
Bam/HWT-3LW-wing-CnR-K9me3-sup-rep1_dm6-sacCer3_trim_q5_dupsRemoved.bam
Bam/HWT-3LW-wing-CnR-K9me3-sup-rep1_dm6-sacCer3_trim_q5_dupsRemoved.bam.bai
```

**Comment by snystrom** [comment]
Progress! 

Try `snakemake --printshellcmds --dryrun -j1 Bam/HWT-3LW-wing-CnR-K9me3-sup-rep1_dm6-sacCer3_trim_q5_dupsRemoved.bam` and see what it spits out.

**Comment by 14stutzmanav** [comment]
Wait wait. Ignore what I sent earlier. This is what I put in:
```
rule removeDups:
        input:
                'Bam/{sample, (!?-pooled)}_' + combinedGenome + '_trim_q5_dupsMarked.bam'
        output:     
                bam = 'Bam/{sample}_' +  combinedGenome + '_trim_q5_dupsRemoved.bam',
                index = 'Bam/{sample}_' + combinedGenome + '_trim_q5_dupsRemoved.bam.bai'
        wildcard_constraints:
                sample =".(?!*-pooled)"
        envmodules: 
                modules['samtoolsVer']
        shell:      
                """
                samtools view -@ 4 -bF 0x400 {input} > {output.bam} &&
                samtools index {output.bam} {output.index} 
                """ 
```

This is the error I get
```
[alexisv7@longleaf-login4 cutNrun-pipeline-bioReps]$ bash dryrunSnakemake.sh Snakefile 
/pine/scr/a/l/alexisv7/cnr-analysis/cutNrun-pipeline-bioReps/preProcessSampleConfig.py:40: FutureWarning: read_table is deprecated, use read_csv instead.
  df = pd.read_table(path, delimiter = fileDelimiter)
Wildcard constraints in inputs are ignored.
Building DAG of jobs...
IOFileException in line 294 of /pine/scr/a/l/alexisv7/cnr-analysis/cutNrun-pipeline-bioReps/Snakefile:
nothing to repeat at position 20 in wildcard statement
```

**Comment by 14stutzmanav** [comment]
Ope! Progressed again.
Now I have 
```
wildcard_constraints:
        sample =".(?!-pooled)"
```

Error:
```
[alexisv7@longleaf-login4 cutNrun-pipeline-bioReps]$ snakemake --printshellcmds --dryrun -j1 Bam/HWT-3LW-wing-CnR-K9me3-sup-rep1_dm6-sacCer3_trim_q5_dupsRemoved.bam
/pine/scr/a/l/alexisv7/cnr-analysis/cutNrun-pipeline-bioReps/preProcessSampleConfig.py:40: FutureWarning: read_table is deprecated, use read_csv instead.
  df = pd.read_table(path, delimiter = fileDelimiter)
Wildcard constraints in inputs are ignored.
Building DAG of jobs...
MissingRuleException:
No rule to produce Bam/HWT-3LW-wing-CnR-K9me3-sup-rep1_dm6-sacCer3_trim_q5_dupsRemoved.bam (if you use input functions make sure that they don't raise unexpected exceptions).
```

**Comment by snystrom** [comment]
Ok cool, repeat with: 

`snakemake --printshellcmds --dryrun -j1 Bam/HWT-3LW-wing-CnR-K9me3-sup-rep1_dm6-sacCer3_trim_q5_dupsMarked.bam`

This style of debugging is really useful for snakemake. You walk backwards through the rules to see how it's filling out the wildcards.

**Comment by 14stutzmanav** [comment]
That runs.

**Comment by snystrom** [comment]
Great. I think what this means is the wildcard constraint is excluding a good sample, so needs tweaking.

**Comment by snystrom** [comment]
What happens with:

```
rule removeDups:
        input:
                'Bam/{sample}_' + combinedGenome + '_trim_q5_dupsMarked.bam'
        output:     
                bam = 'Bam/{sample}_' +  combinedGenome + '_trim_q5_dupsRemoved.bam',
                index = 'Bam/{sample}_' + combinedGenome + '_trim_q5_dupsRemoved.bam.bai'
        wildcard_constraints:
                sample =".(?!*-pooled)"
        envmodules: 
                modules['samtoolsVer']
        shell:      
                """
                samtools view -@ 4 -bF 0x400 {input} > {output.bam} &&
                samtools index {output.bam} {output.index} 
                """ 
```

**Comment by 14stutzmanav** [comment]
DupsMarked runs, dupsRemoved looks like this:

```
[alexisv7@longleaf-login4 cutNrun-pipeline-bioReps]$ snakemake --printshellcmds --dryrun -j1 Bam/HWT-3LW-wing-CnR-K9me3-sup-rep1_dm6-sacCer3_trim_q5_dupsRemoved.bam
/pine/scr/a/l/alexisv7/cnr-analysis/cutNrun-pipeline-bioReps/preProcessSampleConfig.py:40: FutureWarning: read_table is deprecated, use read_csv instead.
  df = pd.read_table(path, delimiter = fileDelimiter)
Wildcard constraints in inputs are ignored.
Building DAG of jobs...
IOFileException in line 294 of /pine/scr/a/l/alexisv7/cnr-analysis/cutNrun-pipeline-bioReps/Snakefile:
nothing to repeat at position 20 in wildcard statement
```

**Comment by snystrom** [comment]
Oh tweak to:

```
wildcard_constraints:
                sample ="((?!-pooled).)*"
```

I think this is the correct pattern to perform a negative lookahead in python regex.

**Comment by 14stutzmanav** [comment]
They both run!! 🎉 

Now when I try to submit the whole pipeline I'm seeing an missing input error downstream:
```
/pine/scr/a/l/alexisv7/cnr-analysis/cutNrun-pipeline-bioReps/preProcessSampleConfig.py:40: FutureWarning: read_table is deprecated, use read_csv instead.
  df = pd.read_table(path, delimiter = fileDelimiter)
Wildcard constraints in inputs are ignored.
Building DAG of jobs...
MissingInputException in line 347 of /pine/scr/a/l/alexisv7/cnr-analysis/cutNrun-pipeline-bioReps/Snakefile:
Missing input files for rule splitSpecies:
Bam/HWT-3LW-wing-CnR-K9me3-sup-rep1-pooled_dm6-sacCer3_trim_q5_dupsRemoved.bam.bai
```

**Comment by snystrom** [comment]
Ah, add `samtools index` to the merge step and add the `.bai` file to the outputs!

**Comment by snystrom** [comment]
Then you should be good to go!

**Comment by 14stutzmanav** [comment]
WOOHOO!! It runs! 🎉 

Thank you SO MUCH for all your help!

**Comment by snystrom** [comment]
Happy CUT&RUNing!

**Comment by snystrom** [comment]
Watch the times on that merge & index step, it may put you in slurm jail.

**Comment by 14stutzmanav** [comment]
Yes! I'll do a practice run and check the times before I bring it to the rest of the lab. Now I have to be careful- I'm sure I'm on slurm probation!!
